<?php
/**
 * Database Configuration
 * Auto-generated by setup.php
 * 
 * NOTE: Connection is handled by Database singleton class (core/Database.php)
 */

define('DB_HOST', 'localhost');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_NAME', 'topinv');

// JWT Secret for authentication
define('JWT_SECRET', 'topinv_secret_key_change_in_production');
?>
