<?php
/**
 * Database Configuration
 * Auto-generated by setup.php
 */

define('DB_HOST', 'localhost');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_NAME', 'topinv');

// Database connection
$GLOBALS['db'] = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);

if ($GLOBALS['db']->connect_error) {
    die(json_encode(['success' => false, 'message' => 'Database connection failed']));
}

$GLOBALS['db']->set_charset('utf8mb4');
?>
