<?php
/**
 * TOPINV Database Migration & Setup Script
 * 
 * THIS IS A SETUP FILE - RUN ONCE TO INITIALIZE DATABASE
 * 
 * Usage: Visit http://localhost/topinv/backend/setup.php in browser
 * or run: php setup.php in terminal
 */

// Suppress warnings during setup
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Database credentials
define('DB_HOST', 'localhost');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_NAME', 'topinv');

$response = [
    'success' => false,
    'message' => '',
    'steps' => []
];

try {
    // Step 1: Connect to MySQL (without selecting database initially)
    if (php_sapi_name() === 'cli') {
        echo "\nTOPINV Database Setup\n";
        echo str_repeat("=", 50) . "\n\n";
    } else {
        echo "<h2>TOPINV Database Setup</h2>";
        echo "<pre>";
    }
    
    $conn = new mysqli(DB_HOST, DB_USER, DB_PASS);
    if ($conn->connect_error) {
        throw new Exception("Connection failed: " . $conn->connect_error);
    }
    echo "[✓] Connected to MySQL\n";
    $response['steps'][] = 'Connected to MySQL Server';
    
    // Step 2: Read and execute database schema
    $schema_file = __DIR__ . '/database.sql';
    if (!file_exists($schema_file)) {
        throw new Exception("database.sql not found at: " . $schema_file);
    }
    
    // First drop existing database if it exists
    $drop_db_sql = "DROP DATABASE IF EXISTS " . DB_NAME;
    if (!$conn->query($drop_db_sql)) {
        // Ignore drop errors if database doesn't exist
    }
    echo "[✓] Cleaned old database\n";
    
    // Create the database fresh
    $create_db_sql = "CREATE DATABASE " . DB_NAME . " CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci";
    if (!$conn->query($create_db_sql)) {
        throw new Exception("Error creating database: " . $conn->error);
    }
    echo "[✓] Created database\n";
    
    // Select the database
    if (!$conn->select_db(DB_NAME)) {
        throw new Exception("Cannot select database: " . $conn->error);
    }
    echo "[✓] Selected database\n";
    
    // Read schema file
    $schema_content = file_get_contents($schema_file);
    
    // Remove comments and database operations
    $lines = explode("\n", $schema_content);
    $filtered_lines = [];
    foreach ($lines as $line) {
        $trimmed = trim($line);
        // Skip comments and CREATE DATABASE / USE statements
        if (!preg_match('/^(----|CREATE DATABASE|USE )/', $trimmed)) {
            $filtered_lines[] = $line;
        }
    }
    $schema_content = implode("\n", $filtered_lines);
    
    // Split by semicolon and execute each statement
    $statements = array_filter(
        array_map('trim', explode(';', $schema_content)),
        function($stmt) {
            return !empty($stmt);
        }
    );
    
    $executed = 0;
    foreach ($statements as $statement) {
        if (empty(trim($statement))) {
            continue;
        }
        
        if (!$conn->multi_query($statement)) {
            throw new Exception("Error executing statement: " . $conn->error . "\nStatement: " . substr($statement, 0, 100) . "...");
        }
        
        // Process multiple results
        do {
            if ($result = $conn->store_result()) {
                $result->free();
            }
        } while ($conn->next_result());
        
        $executed++;
    }
    
    echo "[✓] Executed " . $executed . " SQL statements\n";
    $response['steps'][] = "Executed {$executed} SQL statements";
    
    // Step 3: Verify database structure
    $tables_query = "SELECT COUNT(*) as count FROM information_schema.TABLES WHERE TABLE_SCHEMA = '" . DB_NAME . "'";
    $result = $conn->query($tables_query);
    $row = $result->fetch_assoc();
    $table_count = $row['count'];
    
    echo "[✓] Verified " . $table_count . " tables created\n";
    $response['steps'][] = "Verified {$table_count} tables in database";
    
    // Step 4: Verify initial data
    $users_count = $conn->query("SELECT COUNT(*) as count FROM users")->fetch_assoc()['count'];
    $products_count = $conn->query("SELECT COUNT(*) as count FROM products")->fetch_assoc()['count'];
    $periods_count = $conn->query("SELECT COUNT(*) as count FROM periods")->fetch_assoc()['count'];
    
    echo "[✓] Inserted initial data:\n";
    echo "    - Users: " . $users_count . "\n";
    echo "    - Products: " . $products_count . "\n";
    echo "    - Periods: " . $periods_count . "\n";
    
    $response['steps'][] = "Inserted initial data: {$users_count} users, {$products_count} products, {$periods_count} periods";
    
    // Step 5: Create config file for backend
    $config_content = "<?php\n";
    $config_content .= "/**\n";
    $config_content .= " * Database Configuration\n";
    $config_content .= " * Auto-generated by setup.php\n";
    $config_content .= " */\n\n";
    $config_content .= "define('DB_HOST', 'localhost');\n";
    $config_content .= "define('DB_USER', 'root');\n";
    $config_content .= "define('DB_PASS', '');\n";
    $config_content .= "define('DB_NAME', 'topinv');\n\n";
    $config_content .= "// Database connection\n";
    $config_content .= "\$GLOBALS['db'] = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);\n\n";
    $config_content .= "if (\$GLOBALS['db']->connect_error) {\n";
    $config_content .= "    die(json_encode(['success' => false, 'message' => 'Database connection failed']));\n";
    $config_content .= "}\n\n";
    $config_content .= "\$GLOBALS['db']->set_charset('utf8mb4');\n";
    $config_content .= "?>\n";
    
    file_put_contents(__DIR__ . '/config.php', $config_content);
    echo "[✓] Created config.php\n";
    $response['steps'][] = 'Created config.php';
    
    // Step 6: Create a status file
    $env_status = "TOPINV_DB_INITIALIZED=" . date('Y-m-d H:i:s') . "\n";
    file_put_contents(__DIR__ . '/.setup-complete', $env_status);
    echo "[✓] Setup complete\n";
    
    echo "\n";
    $response['success'] = true;
    $response['message'] = 'Database and tables created successfully!';
    
    if (php_sapi_name() !== 'cli') {
        echo "</pre>";
    }
    
    // Display credentials
    if (php_sapi_name() !== 'cli') {
        echo "<h3>Database Credentials</h3>";
        echo "<table border='1' cellpadding='10'>";
        echo "<tr><td><strong>Host:</strong></td><td>" . DB_HOST . "</td></tr>";
        echo "<tr><td><strong>Database:</strong></td><td>" . DB_NAME . "</td></tr>";
        echo "<tr><td><strong>User:</strong></td><td>" . DB_USER . "</td></tr>";
        echo "<tr><td><strong>Tables Created:</strong></td><td>" . $table_count . "</td></tr>";
        echo "<tr><td><strong>Demo Users:</strong></td><td>" . $users_count . "</td></tr>";
        echo "</table>";
        
        // Demo credentials
        echo "<h3>Demo Login Credentials (Password: 'password')</h3>";
        echo "<ul>";
        echo "<li><strong>Cashier:</strong> username: cashier1</li>";
        echo "<li><strong>Admin:</strong> username: admin1</li>";
        echo "</ul>";
        
        echo "<h3>Database Tables Created:</h3>";
        echo "<ul>";
        echo "<li>users - User accounts with roles (cashier, admin)</li>";
        echo "<li>products - Product reference data (immutable opening_stock)</li>";
        echo "<li>transactions - Append-only transaction log (PURCHASE, SALE, ADJUSTMENT, REVERSAL, VOID)</li>";
        echo "<li>draft_sales - Temporary draft sales before commitment</li>";
        echo "<li>draft_sale_items - Line items in draft sales</li>";
        echo "<li>periods - Period management (OPEN/CLOSED status)</li>";
        echo "<li>audit_logs - Immutable audit trail of all actions</li>";
        echo "<li>stock_adjustments - Stock counting variance tracking</li>";
        echo "</ul>";
        
        echo "<h3>Key Features Enabled:</h3>";
        echo "<ul>";
        echo "<li>✓ Append-only transaction model (no deletes)</li>";
        echo "<li>✓ Stock derived from transactions (no direct edits)</li>";
        echo "<li>✓ Period locking (CLOSED periods are read-only)</li>";
        echo "<li>✓ Reversal workflows for corrections</li>";
        echo "<li>✓ Immutable audit logs</li>";
        echo "<li>✓ Atomic stock updates with stored procedures</li>";
        echo "<li>✓ Role-based access control (cashier vs admin)</li>";
        echo "</ul>";
        
        echo "<h3>Next Steps</h3>";
        echo "<ol>";
        echo "<li>Update demo user passwords in production (currently hashed for 'password')</li>";
        echo "<li>Visit <a href='/topinv/public/index.html' target='_blank'>Login Page</a> to test the application</li>";
        echo "<li>Review backend services in /backend/services/ for API endpoints</li>";
        echo "<li>Test transaction workflows (sales, purchases, adjustments)</li>";
        echo "</ol>";
        
        echo "<hr>";
        echo "<h3 style='color: #0284c7;'>✓ Setup Successful!</h3>";
        echo "<p>The database has been initialized with all required tables and procedures.</p>";
    } else {
        echo "\n=== Setup Complete ===\n";
        echo "Status: SUCCESS ✓\n\n";
        echo "Database: " . DB_NAME . "\n";
        echo "Tables Created: " . $table_count . "\n";
        echo "Demo Users: " . $users_count . "\n";
        echo "Demo Products: " . $products_count . "\n";
        echo "\nDemo Credentials:\n";
        echo "  Cashier: cashier1 (password)\n";
        echo "  Admin: admin1 (password)\n";
    }
    
    $conn->close();
    
} catch (Exception $e) {
    $response['success'] = false;
    $response['message'] = $e->getMessage();
    
    if (php_sapi_name() !== 'cli') {
        echo "</pre>";
        echo "<h3 style='color: red;'>✗ Setup Failed</h3>";
        echo "<p><strong>Error:</strong> " . htmlspecialchars($e->getMessage()) . "</p>";
    } else {
        echo "\nERROR: " . $e->getMessage() . "\n";
    }
}

// If called via API, return JSON
if (isset($_GET['json'])) {
    header('Content-Type: application/json');
    echo json_encode($response);
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>TOPINV Setup</title>
    <style>
        body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; 
            margin: 40px; 
            background: #f8f9fa;
            color: #333;
        }
        h2, h3 { color: #0284c7; margin-top: 25px; }
        h2 { border-bottom: 3px solid #0284c7; padding-bottom: 10px; }
        table { 
            border-collapse: collapse; 
            margin: 20px 0; 
            background: white;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        table td { 
            padding: 12px; 
            border: 1px solid #e0e0e0; 
        }
        table tr:first-child { background: #e0f2fe; }
        pre { 
            background: #f5f5f5; 
            padding: 15px; 
            overflow-x: auto; 
            border-left: 4px solid #0284c7;
            font-family: 'Courier New', monospace;
        }
        .success { color: #0284c7; font-weight: bold; }
        .error { color: #dc2626; font-weight: bold; }
        ul, ol { line-height: 1.8; }
        a { color: #0284c7; }
        hr { margin: 30px 0; border: none; border-top: 1px solid #e0e0e0; }
    </style>
</head>
<body>
</body>
</html>
